### ISSUE TITLE
400 error when metric_usage_client is prom analytics proxy

### ISSUE THREAD

**Issue by liaeden100** [nicolastakashi/prom-analytics-proxy#224]
### What did you do?

i have a metrics collector instance connected to my thanos query, and a grafana collector connected to my grafana instance. (url of openshift routes). when i do a get request to /api/v1/metrics i see all the metrics and the usage in dashboard. 
i also have a prom analytics proxy running on open shift. i configured the metrics usage to send the usage to the prom analytics proxy.

i get an 400 error in metrics usage:

`
msg="Failed to send usage for metric" collector=grafana error="when sending metrics usage, unexpected status code: 400"
`

### MetricsUsage version

0.5.0

### MetricsUsage configuration file

```yaml
config:
   metric_collector:
       enable: true
       http_client:
           url: "<http route to the thanos query>"
   grafana_collector:
       enable: true
       metric_usage_client:
            url: "<http route to the prom analytics proxy>"
       grafana_client:
            url: "<http route of the grafana>"
            basic_auth:
             ..... (username and password)
```

i opened an issue about it to the metrics usage project but they said after tests its probably a problem with this project.
